MOOD_TO_GENRES = {
    "melancholic": ["indie folk", "acoustic", "ambient", "slowcore", "singer-songwriter"],
    "fierce": ["trap", "drill", "experimental hip-hop", "bass-heavy grime"],
    "dreamy": ["dream pop", "shoegaze", "ambient pop", "synthwave"],
    "vibey": ["lo-fi", "neo soul", "indie pop", "bedroom pop"],
    "romantic": ["modern r&b", "slow jam", "classic soul", "soft rock"],
    "dark": ["dark techno", "industrial", "goth wave", "dark trap"],
    "chill": ["chillhop", "nu jazz", "downtempo", "lo-fi beats"],
    "intense": ["hard rock", "drum and bass", "industrial metal", "dubstep (heavy bass)"],
    "glam": ["dance pop", "electropop", "glam rock", "hyperpop"],
    "retro": ["synthpop", "disco", "80s rock", "new wave"],
    "cozy": ["folk pop", "coffeehouse acoustic", "light jazz", "soft indie"],
    "nostalgic": ["2000s pop punk", "90s alt rock", "early 2000s R&B", "emo revival"],
    "playful": ["bubblegum pop", "k-pop", "electro swing", "dance-pop"],
    "empowered": ["power pop", "rap anthems", "feminist trap", "electro rock"],
    "aesthetic": ["lo-fi", "ambient chill", "study beats", "instrumental hip-hop"],
    "soft": ["acoustic ballads", "piano pop", "indie acoustic", "soft ambient"],
    "bittersweet": ["alt indie", "melodic acoustic", "emotional pop", "indie ballads"],
    "mysterious": ["trip-hop", "dark wave", "cinematic ambient", "experimental electronic"],
    "haunting": ["dark ambient", "gothic folk", "post-punk", "drone"],
    "introspective": ["indie folk", "lo-fi instrumental", "ambient", "spoken word blends"],
    "reflective": ["post-rock", "neo-classical", "ambient guitar", "soft indie"],
    "black & white": ["jazz noir", "modern classical", "lo-fi jazz", "blues", "ambient minimalism"]
}
